hours_query <- paste("SELECT M2_AGREEMENT_PROPERTY.AGRP_PRP_ID,",
                     "M2_WORK_TASK.WT_AGRPROP_ID,",
                     "M2_WORK_TASK_UOM.WTM_WT_ID,",
                     "M2_WORK_TASK.WT_EMP_ID,",
                     "M2_WORK_TASK.WT_WORK_DATE,",
                     "M2_WORK_TASK_UOM.WTM_QTY,",
                     "M2_UNIT_OF_MEASURE.UOM_NAME,",
                     "M2_DAMAGE_AGENT.ID,",
                     "M2_DAMAGE_AGENT.DA_NAME,",
                     "M2_COMPONENT.CMP_NAME,",
                     "M2_COMPONENT.CMP_TYPE,",
                     "M2_WORK_TASK.WT_STATE,",
                     "M2_COUNTY.CNTY_NAME,",
                     "M2_PROPERTY.PRP_NAME,",
                     "M2_PROPERTY_UOL.PRPU_N_LAT,",
                     "M2_PROPERTY_UOL.PRPU_E_LONG,",
                     "M2_USE_TYPE.USET_NAME",
                     "FROM M2_WORK_TASK",
                     "INNER JOIN M2_CONFLICT_WORK",
                     "ON M2_WORK_TASK.ID = M2_CONFLICT_WORK.CNFW_WT_ID",
                     "INNER JOIN M2_DAMAGE_AGENT",
                     "ON M2_DAMAGE_AGENT.ID = M2_CONFLICT_WORK.CNFW_DA_ID",
                     "INNER JOIN M2_WORK_TASK_UOM",
                     "ON M2_WORK_TASK.ID = M2_WORK_TASK_UOM.WTM_WT_ID",
                     "INNER JOIN M2_UNIT_OF_MEASURE",
                     "ON M2_UNIT_OF_MEASURE.ID = M2_WORK_TASK_UOM.WTM_UOM_ID",
                     "LEFT JOIN M2_AGREEMENT_PROPERTY",
                     "ON M2_AGREEMENT_PROPERTY.ID = M2_WORK_TASK.WT_AGRPROP_ID",
                     "LEFT JOIN M2_WORK_TASK_COMPONENT",
                     "ON M2_WORK_TASK_COMPONENT.WTC_WT_ID = M2_WORK_TASK.ID",
                     "LEFT JOIN M2_COMPONENT",
                     "ON M2_COMPONENT.ID = M2_WORK_TASK_COMPONENT.WTC_CMP_ID",
                     "LEFT JOIN M2_PROPERTY",
                     "ON M2_PROPERTY.ID = M2_AGREEMENT_PROPERTY.AGRP_PRP_ID",
                     "LEFT JOIN M2_COUNTY",
                     "ON M2_PROPERTY.PRP_CNTY_ID = M2_COUNTY.ID",
                     "LEFT JOIN M2_PROPERTY_UOL",
                     "ON M2_PROPERTY_UOL.PRPU_PRP_ID = M2_PROPERTY.ID",
                     "LEFT JOIN M2_USE_TYPE",
                     "ON M2_USE_TYPE.ID = M2_WORK_TASK_COMPONENT.WTC_USET_ID",
                     "WHERE M2_DAMAGE_AGENT.ID=8 ",
                     "AND WT_WORK_DATE>='01-SEP-20'",
                     "AND WT_STATE='MO'",
                     "AND CMP_NAME!='SNARES, NECK'")